dist: bionic

language: ruby
rvm:
  - 2.7.0

service:
  - docker

jobs:
  inculde:
    - stage: test
      scripts: ./scripts/test.sh
    - stage: deploy
      scripts: ./scripts/deploy.sh

stages:
  - test
  - deploy